set version of scipy to 0.18 in travis
Older versions fails three Figure tests with the same issue:
    self.array[0][maskIndeces] = availIndeces[i]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 600 but corresponding boolean dimension is 599

in scipy 0.18 this "only" produces a warning.

This should be fixed in develop, so it's a temporary version limit-